# DigitalOcean App Platform Specification

name: tsl-ui
region: fra1

services:
  - name: web
    dockerfile_path: Dockerfile

    github:
      branch: main
      deploy_on_push: true
      repo: rhotimee/tsl-ui

    # Build configuration
    build_command: ''

    # Runtime configuration
    http_port: 3000
    instance_count: 1
    instance_size_slug: basic-xxs

    # Routes
    routes:
      - path: /

    health_check:
      http_path: /
      initial_delay_seconds: 5
      period_seconds: 30
      timeout_seconds: 3
      success_threshold: 1
      failure_threshold: 3

    # Environment variables
    envs:
      - key: NODE_ENV
        value: 'production'
      - key: PORT
        value: '3000'
      - key: HOSTNAME
        value: '0.0.0.0'
